<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir).'/wp_ib_hr';

return array(
    'Psr\\Log\\' => array($vendorDir . '/psr/log'),
);
