<?php return array(
    'root' => array(
        'name' => '10quality/wpmvc',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => '96e3e0b86a2d92453455da722dac751bbb02cf06',
        'type' => 'project',
        'install_path' => __DIR__ . '/../../wp_ib_hr',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        '10quality/ayuco' => array(
            'pretty_version' => 'v1.0.5',
            'version' => '1.0.5.0',
            'reference' => '7ccc56bfae47dcc3dba6f257a2ce5b2aa40f744a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../10quality/ayuco',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        '10quality/gettext-wp-scanner' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'reference' => 'f2109db81b952e411ebbce88a8bd8c28054eda3a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../10quality/gettext-wp-scanner',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        '10quality/wp-file' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'reference' => '6bfb7de165082e06c82462532768cc7ae7fc4b4e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../10quality/wp-file',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        '10quality/wpmvc' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '96e3e0b86a2d92453455da722dac751bbb02cf06',
            'type' => 'project',
            'install_path' => __DIR__ . '/../../wp_ib_hr',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        '10quality/wpmvc-commands' => array(
            'pretty_version' => 'v1.1.18',
            'version' => '1.1.18.0',
            'reference' => 'f64dcbac2c52909e33f252a17f03b9ef66440419',
            'type' => 'library',
            'install_path' => __DIR__ . '/../10quality/wpmvc-commands',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        '10quality/wpmvc-core' => array(
            'pretty_version' => 'v3.1.18',
            'version' => '3.1.18.0',
            'reference' => '555e005bd71a16b5f143b316793711c3fb614e33',
            'type' => 'library',
            'install_path' => __DIR__ . '/../10quality/wpmvc-core',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        '10quality/wpmvc-logger' => array(
            'pretty_version' => 'v2.0.x-dev',
            'version' => '2.0.9999999.9999999-dev',
            'reference' => '603fe1a295f6e12b7fea9ca7e4ce80db6f7270e6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../10quality/wpmvc-logger',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        '10quality/wpmvc-mvc' => array(
            'pretty_version' => 'v2.1.15',
            'version' => '2.1.15.0',
            'reference' => 'f3d2a743fef3b219502c56de0a84c0cb96c1fde8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../10quality/wpmvc-mvc',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        '10quality/wpmvc-phpfastcache' => array(
            'pretty_version' => 'v4.0.5',
            'version' => '4.0.5.0',
            'reference' => 'a97d06c83021ee1b254e366079d1427a87654ba3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../10quality/wpmvc-phpfastcache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'deliciousbrains/wp-background-processing' => array(
            'pretty_version' => '1.3.1',
            'version' => '1.3.1.0',
            'reference' => '6d1e48165e461260075b9f161b3861c7278f71e7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../deliciousbrains/wp-background-processing',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'gettext/gettext' => array(
            'pretty_version' => 'v5.7.0',
            'version' => '5.7.0.0',
            'reference' => '8657e580747bb3baacccdcebe69cac094661e404',
            'type' => 'library',
            'install_path' => __DIR__ . '/../gettext/gettext',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'gettext/js-scanner' => array(
            'pretty_version' => 'v1.1.2',
            'version' => '1.1.2.0',
            'reference' => '371bddca27b29eea5d553aade324c8e631ac3444',
            'type' => 'library',
            'install_path' => __DIR__ . '/../gettext/js-scanner',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'gettext/languages' => array(
            'pretty_version' => '2.10.0',
            'version' => '2.10.0.0',
            'reference' => '4d61d67fe83a2ad85959fe6133d6d9ba7dddd1ab',
            'type' => 'library',
            'install_path' => __DIR__ . '/../gettext/languages',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'gettext/php-scanner' => array(
            'pretty_version' => 'v1.3.1',
            'version' => '1.3.1.0',
            'reference' => '989a2cffa1d0f43d13b14c83a50429119b5eb8e4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../gettext/php-scanner',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '7.8.1',
            'version' => '7.8.1.0',
            'reference' => '41042bc7ab002487b876a0683fc8dce04ddce104',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/promises' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => 'bbff78d96034045e58e13dedd6ad91b5d1253223',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/promises',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '2.6.2',
            'version' => '2.6.2.0',
            'reference' => '45b30f99ac27b5ca93cb4831afe16285f57b8221',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'imangazaliev/didom' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'reference' => '50fa6595d14f22c0c984efed5c818485cf548136',
            'type' => 'library',
            'install_path' => __DIR__ . '/../imangazaliev/didom',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'jakub-onderka/php-console-color' => array(
            'dev_requirement' => true,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'mck89/peast' => array(
            'pretty_version' => 'v1.16.2',
            'version' => '1.16.2.0',
            'reference' => '2791b08ffcc1862fe18eef85675da3aa58c406fe',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mck89/peast',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'nikic/php-parser' => array(
            'pretty_version' => 'v4.19.1',
            'version' => '4.19.1.0',
            'reference' => '4e1b88d21c69391150ace211e9eaf05810858d0b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nikic/php-parser',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'paragonie/random_compat' => array(
            'pretty_version' => 'v9.99.100',
            'version' => '9.99.100.0',
            'reference' => '996434e5492cb4c3edcb9168db6fbb1359ef965a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/random_compat',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'paragonie/sodium_compat' => array(
            'pretty_version' => 'v1.21.1',
            'version' => '1.21.1.0',
            'reference' => 'bb312875dcdd20680419564fe42ba1d9564b9e37',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/sodium_compat',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'php-parallel-lint/php-console-color' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'reference' => '7adfefd530aa2d7570ba87100a99e2483a543b88',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-parallel-lint/php-console-color',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'psr/http-client' => array(
            'pretty_version' => '1.0.3',
            'version' => '1.0.3.0',
            'reference' => 'bb5906edc1c324c9a05aa0873d40117941e5fa90',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-client',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-factory' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => '2b4765fddfe3b508ac62f829e852b1501d3f6e8a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-factory-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => '2.0',
            'version' => '2.0.0.0',
            'reference' => '402d35bcb92c70c026d1a6a9883f06b2ead23d71',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'fe0936ee26643249e916849d48e3a51d5f5e278b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pusher/pusher-php-server' => array(
            'pretty_version' => '7.2.4',
            'version' => '7.2.4.0',
            'reference' => 'de2f72296808f9cafa6a4462b15a768ff130cddb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pusher/pusher-php-server',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v2.5.3',
            'version' => '2.5.3.0',
            'reference' => '80d075412b557d41002320b96a096ca65aa2c98d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
